"""
This application is a Text-to-SQL tool.
It allows a user to type a question in plain English, uses Google's Gemini AI to convert that English 
question into a valid SQL database query, and then executes that query against a local SQLite database 
to return the answer.

Below, we break down exactly what each section of the code is doing and WHY we are doing it.
"""

# ---------------------------------------------------------
# 1. Loading Environment Variables
# ---------------------------------------------------------
# We use the dotenv library to load our secret API keys from a hidden .env file.
# This prevents us from hardcoding passwords or API keys directly into the script,
# which is a major security best practice in software engineering.
from dotenv import load_dotenv
load_dotenv() 

# ---------------------------------------------------------
# 2. Importing Required Libraries
# ---------------------------------------------------------
import streamlit as st          # Used to quickly build the interactive web interface (UI)
import os                       # Used to read the environment variables (like our API key)
import sqlite3                  # The built-in Python library for connecting to SQLite databases

# We import LangChain components. LangChain is a framework that makes it easy to build AI applications.
# Instead of talking to Gemini raw, LangChain gives us structured templates, pipelines, and parsers 
# to keep our code clean and modular.
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

# ---------------------------------------------------------
# 3. Setting up the AI (Gemini) Function
# ---------------------------------------------------------
def get_gemini_response(question, prompt):
    """
    This function takes the user's plain English question and our system instructions (prompt),
    and sends them to the Gemini AI model to generate an SQL query.
    """
    
    # Initialize the LangChain LLM (Large Language Model) object. 
    # We use 'gemini-2.5-flash' because it is very fast.
    # Temperature=0.3 makes the AI responses more focused and deterministic (less random),
    # which is exactly what we want when generating strict code like SQL where creativity causes syntax errors.
    llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0.3)
    
    # We create a ChatPromptTemplate. This acts like a mold. 
    # We define a "system" message (the strict rules the AI must follow about our database schema) 
    # and a "human" message (the actual question the user types on the website).
    chat_prompt = ChatPromptTemplate.from_messages([
        ("system", prompt[0]),
        ("human", "{question}")
    ])
    
    # Here we build an LCEL (LangChain Expression Language) pipeline using the '|' pipe operator.
    # It passes the user's question into the prompt mold -> sends it to the LLM -> then extracts the raw text output.
    chain = chat_prompt | llm | StrOutputParser()
    
    # We execute the pipeline by passing in the actual question from the user.
    response = chain.invoke({"question": question})
    return response

# ---------------------------------------------------------
# 4. Setting up the Database Connection
# ---------------------------------------------------------
def read_sql_query(sql, db):
    """
    This function takes the SQL query generated by Gemini and actually runs it
    against our local SQLite database.
    """
    # Create a connection to the local database file (student.db)
    conn = sqlite3.connect(db)
    
    # Create a cursor object. The cursor is the tool that actually executes the SQL commands inside the database.
    cur = conn.cursor()
    
    # Run the SQL query against the database
    cur.execute(sql)
    
    # Fetch all the matching rows from the database table that resulted from our query
    rows = cur.fetchall()
    
    # Save any changes and close the database connection to free up system memory and avoid locking the file
    conn.commit()
    conn.close()
    
    # Loop through the rows and print them to the terminal console (useful for debugging)
    for row in rows:
        print(row)
        
    return rows

# ---------------------------------------------------------
# 5. Defining the System Instructions (Prompt)
# ---------------------------------------------------------
# This is the "brain context" of our SQL converter. 
# We explicitly tell Gemini exactly what our database looks like (columns: NAME, SUBJECT, DIVISON, MARKS)
# We give it examples (known as few-shot prompting) so it understands the pattern it needs to follow.
# Crucially, we command it to ONLY return SQL code. If it returns conversational things like "Sure, here is your query!",
# our database will crash because it doesn't understand English, only SQL.
prompt=[
    """
    You are an expert in converting English questions to SQL query!
    The SQL database has the name STUDENT and has the following columns - NAME, SUBJECT, 
    DIVISON, MARKS \n\nFor example,\nExample 1 - How many entries of records are present?, 
    the SQL command will be something like this SELECT COUNT(*) FROM STUDENT ;
    \nExample 2 - Tell me all the students studying in Data Science subject?, 
    the SQL command will be something like this SELECT * FROM STUDENT 
    where SUBJECT="Data Science"; 
    IMPORTANT: Return ONLY the raw SQL query. Do NOT add any conversational text like "I can help with that". Do NOT include markdown formatting like ```sql or ```.
    """
]

# ---------------------------------------------------------
# 6. Building the Streamlit Web Interface
# ---------------------------------------------------------

# Set the title that appears on the actual browser tab
st.set_page_config(page_title="I can Retrieve Any SQL query")

# Set the main visible header on the webpage
st.header("Gemini App To Retrieve SQL Data")

# Create a text box for the user to type their English question
question = st.text_input("Input: ", key="input")

# Create a button that the user clicks to submit their question
submit = st.button("Ask the question")

# When the user clicks the submit button, this 'if' block executes:
if submit:
    # Step 1: Send the question to Gemini to get an SQL query back
    response = get_gemini_response(question, prompt)
    print("Raw Response:", response)
    
    # Step 2: Sanitize (Clean) the AI's output.
    # Even though we told the AI not to use markdown (like ```sql), AI can be stubborn and sometimes still does.
    # This code strips away those extra characters so the database doesn't crash when reading it.
    clean_sql = response.replace("```sql", "").replace("```", "").strip()
    
    # We ensure we only capture the string starting from "SELECT" to avoid any random conversational prefix text
    if "SELECT" in clean_sql.upper():
        clean_sql = clean_sql[clean_sql.upper().find("SELECT"):]
        
    print("Cleaned SQL:", clean_sql)
    
    # Step 3: Run the cleaned SQL query against our database to get the real data
    response = read_sql_query(clean_sql, "student.db")
    
    # Step 4: Display the results pulled from the database onto the web page using Streamlit
    st.subheader("The Response is")
    for row in response:
        print(row)
        st.header(row)
